<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BA Computer Science MajorBA Computer_f32cd8</name>
   <tag></tag>
   <elementGuidId>a4e6c662-c277-49fc-89a6-cb4efc114e09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='degrees']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn dropdown-toggle btn-light </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>degrees</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>degrees</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                BA Computer Science MajorBA Computer Science Major, Data Science MinorBA Computer Science Major, Math MinorBS Actuarial Statistics MajorBS Actuarial Statistics Major, Computer Science MinorBS Actuarial Statistics Major, Data Science MinorBS Applied Math MajorBS Applied Math Major, Computer Science MinorBS Applied Math Major, Data Science MinorBS Computer Science MajorBS Computer Science Major, Data Science MinorBS Computer Science Major, Math MinorBS General Math MajorBS General Math Major, Computer Science MinorBS General Math Major, Data Science MinorBS Mathematics, Secondary Education ConcentrationBS Pure Math MajorBS Pure Math Major, Computer Science MinorBS Pure Math Major, Data Science MinorBS Statistical Science MajorBS Statistical Science Major, Computer Science MinorBS Statistical Science Major, Data Science MinorBSE Comp Engineering Major, Innovation &amp; Entrepreneurship MinorBSE Comp Engineering, Second Concentration in Elec EngineeringBSE Computer Engineering MajorBSE Computer Engineering Major, Computer Science MinorBSE Computer Engineering Major, Math MinorBSE Elec Engineering Major, Innovation &amp; Entrepreneurship MinorBSE Elec Engineering, Second Concentration in Comp EngineeringBSE Electrical Engineering MajorBSE Electrical Engineering Major, Computer Science MinorBSE Electrical Engineering Major, Math MinorBSE Mat Engineering Major, Innovation &amp; Entrepreneurship MinorBSE Mat Engineering, Second Concentration in Mech EngineeringBSE Materials Engineering MajorBSE Materials Engineering Major, Computer Science MinorBSE Materials Engineering Major, Math MinorBSE Mech Engineering Major, Innovation &amp; Entrepreneurship MinorBSE Mech Engineering, Second Concentration in Mat EngineeringBSE Mechanical Engineering MajorBSE Mechanical Engineering Major, Computer Science MinorBSE Mechanical Engineering Major, Math Minor	</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;degrees&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='degrees']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a Degree Combination From the Menu Below:'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loyola University Degree Planner'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'degrees', '&quot;', ')')])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
